### PR TITLE
Update plotlyfig2dash.m with Loading feature

### PR DESCRIPTION
**Pull request by carlosbionic**
Updated plotlyfig2dash.m with Loading feature. Right now while the page is loading, the graph turns invisible and the loading circle appears. After loading, the graph reappears with the corresponding changes.

### CODE REVIEW

**Review by Igor-gomonov — COMMENTED** [review]
after opening in browser, loading animation starts, and when finished, shows clear axes. Moving slider makes it plot correctly. 
Tried to fix it, but it either have no effect or don't show load animation.
Before immediately after tab opening it had scatter plot for first year, and even while loading it never disappeared. 
My opinion it is linux makes such behavior 
2021-08-02-001800_1366x768_scrot

**Comment by jackparmer** [comment]
Same for me, blank graph after loading with the spinner:

image

Then shows up moving the slider

image

**Comment by jackparmer** [comment]
I also get this, inside the browser tab:

image

**Comment by carlosbionic** [comment]
Is this happening without the Loading feature too? After first load, if I wait a couple of seconds clear axes appear.

**Review by Igor-gomonov — APPROVED** [review]
works!

**Comment by jackparmer** [comment]
What is the status of this? Is it working in everyone's MATLAB environment now?

**Comment by Igor-gomonov** [comment]
It works on linux and windows, and should on mac also. We can approve it i think

**Pull request merged**
